{% set name = "pep517" %}
{% set version = "0.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 931378d93d11b298cf511dd634cf5ea4cb249a28ef84160b3247ee9afb4e8ab0

build:
  skip: True  # [py<36]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - flit-core >=2,<4
  run:
    - python
    - importlib_metadata  # [py<38]
    - tomli >=1.1.0  # [py>=36]
    - zipp  # [py<38]

test:
  imports:
    - pep517
  commands:
    # temporarily skipping pip check on win and pypy build because of bizarre tqdm issue
    - pip check  # [not (win and python_impl == 'pypy')]
  requires:
    - pip
    - python <3.10

about:
  home: https://pypi.org/project/pep517/
  summary: Wrappers to build Python packages using PEP 517 hooks
  license: MIT
  license_family: MIT
  license_file: LICENSE
  dev_url: https://github.com/pypa/pep517
  doc_url: https://pep517.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - ocefpaf
